inherit_from: .rubocop_todo.yml

# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://docs.rubocop.org/rubocop/configuration

require:
  - rubocop-rake
  - rubocop-minitest

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5

# == Gemspec ==

Gemspec/RequiredRubyVersion:
  Enabled: false

# == Style ==

Style/Alias:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/CombinableLoops:
  Exclude:
    - test/**/*.rb

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: annotated

Style/Lambda:
  Enabled: false

Style/LambdaCall:
  Enabled: false

Style/ModuleFunction:
  EnforcedStyle: extend_self

Style/RaiseArgs:
  EnforcedStyle: compact

Style/SymbolArray:
  EnforcedStyle: brackets

# == Layout ==

Layout/ArrayAlignment:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBrackets: no_space

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

# == Lint ==

Lint/ConstantDefinitionInBlock:
  Enabled: false

Lint/NestedMethodDefinition:
  Exclude:
    - test/micro/struct/instance_method_test.rb

# == Naming ==

Naming/ClassAndModuleCamelCase:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/u-struct.rb

Naming/MethodParameterName:
  Exclude:
    - examples/**/*.rb

Naming/RescuedExceptionsVariableName:
  PreferredName: exception

# == Metrics ==

Metrics/AbcSize:
  Exclude:
    - test/**/*.rb

Metrics/MethodLength:
  Exclude:
    - test/**/*.rb

Metrics/ClassLength:
  Exclude:
    - test/**/*.rb

# == Minitest ==

Minitest/AssertWithExpectedArgument:
  Enabled: false

Minitest/MultipleAssertions:
  Max: 21
